In [1]:
# python列表->np的ndarray
import numpy as np
list1 = [1, 2, 3, 4]
print(list1)
oneArray = np.array(list1)
print(type(oneArray))
print(oneArray)
# python list打印出来的元素之间有逗号
# 而ndarray是空格

[1, 2, 3, 4]
<class 'numpy.ndarray'>
[1 2 3 4]


In [2]:
# Numpy的数组和原生python的性能对比
import random
import time
import numpy as np

a = []
for i in range(100000000):
   a.append(random.random())
t1 = time.time()
sum1 = sum(a)
t2 = time.time()

b = np.array(a)
t4 = time.time()
sum3 = np.sum(b)
t5 = time.time()
print("python:", t2 - t1, "\n", "NumPy:", t5 - t4)
#np的运算速度是原生py的5倍


python: 0.6491446495056152 
 NumPy: 0.12503528594970703


In [3]:
#传入列表变为ndarray
t1 = np.array([1,2,3])
print(t1)
print(type(t1))


[1 2 3]
<class 'numpy.ndarray'>


In [5]:
# 可以传range
t2 = np.array(range(10))
print(t2)
print(type(t2))
print(list(t2))  # list转回列表


[0 1 2 3 4 5 6 7 8 9]
<class 'numpy.ndarray'>
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [6]:
# np自带arange
t3 = np.arange(0,10,2)
print(t3)
print(type(t3))


[0 2 4 6 8]
<class 'numpy.ndarray'>


In [7]:
#二维数组
import numpy as np
list2 = [[1,2],[3,4],[5,6]]

twoArray = np.array(list2)
print(type(twoArray))
print(twoArray)
# 3行2列


<class 'numpy.ndarray'>
[[1 2]
 [3 4]
 [5 6]]


In [8]:
# 看ndarray的各种属性；最基础、重要
list2 = [[1,2],[3,4],[5,6]]

twoArray = np.array(list2)
# 获取数组的维度( 注意： 与函数的参数很像)
print(twoArray.ndim)

# 形状（行，列）
print(twoArray.shape)

# 有多少个元素
print(twoArray.size)


2
(3, 2)
6


In [15]:
# 形状调整
four = np.array([[1, 2, 3], [4, 5, 6]])
print(id(four))

four1 = four
four.shape = (3, 2)
print(id(four))
print(id(four1))
print(four)
print(four1)
print("*"*50)

# 返回一个新的数组
four = four.reshape(2, 3)
print(four)

# 将多维变成一维数组
five = four.reshape((6,),order='C')
# 默认情况下‘C’以行为主的顺序展开，‘F’（Fortran风格）意味着以列的顺序展开
six = four.flatten(order='C')
print(five)
print(six)
print('-'*50)
# 拓展：数组的形状
t = np.arange(24)
print(t)
print(t.shape)
print(t.ndim)

# 转换成二维
t1 = t.reshape((4,6))
print(t1)
print(t1.shape)

# 转成三维
# 最前面的是零轴，零轴和最外面的括号对应
# 轴越小，越靠外，最小的轴是最外层
t2 = t.reshape((2,3,4))
print(t2)
print(t2.shape)
print(t2.ndim)

2344318112656
2344318112656
2344318112656
[[1 2]
 [3 4]
 [5 6]]
[[1 2]
 [3 4]
 [5 6]]
**************************************************
[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]
[1 2 3 4 5 6]
--------------------------------------------------
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
(24,)
1
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
(4, 6)
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
(2, 3, 4)
3


In [16]:
#将数组转换为列表 tolist
a = np.array([9, 12, 88, 14, 25])
print(type(a))
list_a = a.tolist()  # 新方法
print(type(a))
print(list_a)
print(type(list_a))


<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
[9, 12, 88, 14, 25]
<class 'list'>


In [19]:
# 指定dtype的目的是减少内存的使用，提高运算效率
# np.int8到np.int64（1一个字节到8个字节）
import random
f = np.array([1,2,3,4,5], dtype = np.int16) # 返回数组中每个元素的字节单位长度,dtype设置数据类型
print(f.itemsize) # 2 np.int16(一个字节)
# 获取数据类型
print(f.dtype)

# 调整数据类型
f1 = f.astype(np.int64)  # astype接口
print(f1.dtype)
print(f1.itemsize)  # 8
print("*"*50)

# 拓展随机生成小数
# 使用python语法，round是保留多少位
print(round(random.random(),2))

arr = np.array([random.random() for i in range(10)])
print(arr)
print(arr.itemsize)
print(arr.dtype)
arr1=arr.astype(np.float32)
print(arr1)
# float32精度为6-7位？
# double(float64)精度是15-16位

# 取小数点后两位
print(np.round(arr,2))

2
int16
int64
8
**************************************************
0.67
[0.04410518 0.6658255  0.59583925 0.43407266 0.52193384 0.73109178
 0.06683771 0.41342092 0.9001463  0.23639824]
8
float64
[0.04410518 0.6658255  0.59583926 0.43407264 0.52193385 0.7310918
 0.06683771 0.41342092 0.9001463  0.23639823]
[0.04 0.67 0.6  0.43 0.52 0.73 0.07 0.41 0.9  0.24]


# 数组和数的计算

In [20]:
t1 = np.arange(24).reshape((6,4))
print(t1)
print("-"*20)
t2=t1.tolist()
print(t1+2) #ndarray可以与整数进行加减乘除
# print(t2+2) 不能对列表进行直接加整数操作
print("-"*20)
print(t1*2)
print("-"*20)
print(t1/2)


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
--------------------
[[ 2  3  4  5]
 [ 6  7  8  9]
 [10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]
 [22 23 24 25]]
--------------------
[[ 0  2  4  6]
 [ 8 10 12 14]
 [16 18 20 22]
 [24 26 28 30]
 [32 34 36 38]
 [40 42 44 46]]
--------------------
[[ 0.   0.5  1.   1.5]
 [ 2.   2.5  3.   3.5]
 [ 4.   4.5  5.   5.5]
 [ 6.   6.5  7.   7.5]
 [ 8.   8.5  9.   9.5]
 [10.  10.5 11.  11.5]]


In [21]:
#形状相同,才可以进行加减乘除
t1 = np.arange(24).reshape((6,4))
t3 = np.arange(100,124).reshape((6,4))
print(t1)
print(t3)
print(t1+t3)
print(t1*t3)  #是否是矩阵乘法？ 不是,是对应位置相乘


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
[[100 101 102 103]
 [104 105 106 107]
 [108 109 110 111]
 [112 113 114 115]
 [116 117 118 119]
 [120 121 122 123]]
[[100 102 104 106]
 [108 110 112 114]
 [116 118 120 122]
 [124 126 128 130]
 [132 134 136 138]
 [140 142 144 146]]
[[   0  101  204  309]
 [ 416  525  636  749]
 [ 864  981 1100 1221]
 [1344 1469 1596 1725]
 [1856 1989 2124 2261]
 [2400 2541 2684 2829]]


In [22]:
#shape不同，不能进行运算
# t1 = np.arange(24).reshape((4,6))
# t4 = np.arange(6).reshape((3,2))
# print(t1)
# print(t4)
# print(t1-t4)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
[[0 1]
 [2 3]
 [4 5]]


ValueError: operands could not be broadcast together with shapes (4,6) (3,2) 

In [24]:
#一维数组和二维数组进行运算时，一维的元素个数和列数相等
t1 = np.arange(24).reshape((4,6))
t5 = np.arange(0,6)
print(t1)
print(t5)
t5=t5.reshape((1,6))  # 有无这一步均可运算
print(t5)
print(np.sum(t5))
print(t5.shape)
print(t1-t5)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
[0 1 2 3 4 5]
[0 1 2 3 4 5]
15
(6,)
[[ 0  0  0  0  0  0]
 [ 6  6  6  6  6  6]
 [12 12 12 12 12 12]
 [18 18 18 18 18 18]]


In [25]:
t1 = np.arange(24).reshape((4,6))
t6 = np.arange(4).reshape((4,1))
print(t6)
print(t1)
print(t1-t6)


[[0]
 [1]
 [2]
 [3]]
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
[[ 0  1  2  3  4  5]
 [ 5  6  7  8  9 10]
 [10 11 12 13 14 15]
 [15 16 17 18 19 20]]


# 练习轴


In [26]:
t1=np.arange(1,19).reshape((3,2,3))
print(t1)


[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]]]


In [27]:
# 基于轴的运算
import numpy as np
a = np.array([[1,2,3],[4,5,6]])
print(a)
print(np.sum(a,axis=0)) # [5 7 9]
print("-"*20)
print(np.sum(a,axis=1)) # [ 6 15]
print("-"*20)
print(np.sum(a))
a=np.arange(27).reshape((3,3,3))
print(a)
print("-"*20)
b=np.sum(a, axis=0)
print("-"*20)
print(b)
c=np.sum(a, axis=1)
print("-"*20)
print(c)
d=np.sum(a, axis=2)
print("-"*20)
print(d)

b=np.arange(120).reshape((2,3,4,5))
print(b)
c=np.sum(b,axis=1)
print('-'*50)
print(c)


[[1 2 3]
 [4 5 6]]
[5 7 9]
--------------------
[ 6 15]
--------------------
21
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]
--------------------
--------------------
[[27 30 33]
 [36 39 42]
 [45 48 51]]
--------------------
[[ 9 12 15]
 [36 39 42]
 [63 66 69]]
--------------------
[[ 3 12 21]
 [30 39 48]
 [57 66 75]]
[[[[  0   1   2   3   4]
   [  5   6   7   8   9]
   [ 10  11  12  13  14]
   [ 15  16  17  18  19]]

  [[ 20  21  22  23  24]
   [ 25  26  27  28  29]
   [ 30  31  32  33  34]
   [ 35  36  37  38  39]]

  [[ 40  41  42  43  44]
   [ 45  46  47  48  49]
   [ 50  51  52  53  54]
   [ 55  56  57  58  59]]]


 [[[ 60  61  62  63  64]
   [ 65  66  67  68  69]
   [ 70  71  72  73  74]
   [ 75  76  77  78  79]]

  [[ 80  81  82  83  84]
   [ 85  86  87  88  89]
   [ 90  91  92  93  94]
   [ 95  96  97  98  99]]

  [[100 101 102 103 104]
   [105 106 107 108 109]
   [110 111 112 113 114]
   [115 116 117

# 索引和切片

In [ ]:
import numpy as np

a = np.arange(10)
# 冒号分隔切片参数 start:stop:step 来进行切片操作print(a[2:7:2])# 从索引 2 开始到索引 7 停止，间隔为 2

# 如果只放置一个参数，如 [2]，将返回与该索引相对应的单个元素
print(a[2],a)

# 如果为 [2:]，表示从该索引开始以后的所有项都将被提取
print(a[2:])


In [ ]:
import numpy as np
t1 = np.arange(24).reshape(4,6)
print(t1)
print('*'*20)
print(t1[1]) # 取一行(一行代表是一条数据，索引也是从0开始的) print(t1[1,:]) # 取一行
print('*'*20)
print(t1[1:])# 取连续的多行
print('*'*20)
print(t1[1:3,:])# 取连续的多行
print('*'*20)
print(t1[[0,2,3]])# 取不连续的多行
print('*'*20)
print(t1[[0,2,3],:])# 取不连续的多行
print('*'*20)
print(t1[:,1])# 取一列
print('*'*20)
print(t1[:,1:])# 连续的多列
print('*'*20)
print(t1[:,[0,2,3]])# 取不连续的多列
print('*'*20)
print(t1[2,3])# # 取某一个值,三行四列  py是t1[2][3]
print('*'*20)
print(t1[[0,1,1],[0,1,3]])# 取多个不连续的值，[[行，行。。。],[列，列。。。]]

